// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnfgcszteimigemxdcyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuZmdjc3p0ZWltaWdlbXhkY3lyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTk1NTEsImV4cCI6MjA2ODQzNTU1MX0.Cf0a-jmp7gAEWad_ze9p6fxuX38b6Jy58GbC8dCLRcI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});